name: "Terraform Init"
description: "Terraform Init Composite Action"
inputs:
  tf-version:
    required: true
    description: "Terraform Version"
  aws-region:
    required: true
    description: "AWS Region"
  tf-directory:
      required: false
      description: "Working directory"
  terraform-wrapper:
    required: true
    description: "Terraform Wrapper"
  local-execution-mode:
    required: false
    description: "Terraform Cloud/Enterprise Workspace Local Execution Mode flag"
  terraform-execution-iam-role-arn:
    required: false
    description: "Terraform Execution IAM Role ARN"

outputs:
  outcome:
    description: "Terraform init command outcome"
    value: ${{ steps.init.outcome }}
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf-version }}
        terraform_wrapper: ${{ inputs.terraform-wrapper }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      if: ${{ inputs.local-execution-mode == 'true' }}
      with:
        role-to-assume: ${{ inputs.terraform-execution-iam-role-arn }}
        role-session-name: terraform-execution-role
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 1200
    - name: Terraform Init
      id: init
      shell: bash
      working-directory: ${{ inputs.tf-directory}}
      run: terraform init